### ISSUE TITLE
This file will interest you

### ISSUE THREAD

**Issue by phdussud** [nic3-14159/CH347-Research#1]
Please take a look at the beginning of  [https://github.com/WCHSoftGroup/ch347/blob/main/ch347_jtag.c](https://github.com/WCHSoftGroup/ch347/blob/main/ch347_jtag.c). It contains definitions of instructions for reading and writing in JTAG mode
Like this:
#define HW_TDO_BUF_SIZE              4096
#define SF_PACKET_BUF_SIZE           51200 //命令包长度
#define UCMDPKT_DATA_MAX_BYTES_USBHS 507   // USB高速时每个命令包内包含数据长度
#define USBC_PACKET_USBHS            512   // USB高速时单包最大数据长度

#define CH347_CMD_HEADER 3 //协议包头长度

// 协议传输格式：CMD（1字节）+ Length（2字节）+ Data
#define CH347_CMD_INFO_RD            0xCA //参数获取,用于获取固件版本、JTAG接口相关参数等
#define CH347_CMD_JTAG_INIT          0xD0 // JTAG接口初始化命令
#define CH347_CMD_JTAG_BIT_OP        0xD1 // JTAG接口引脚位控制命令
#define CH347_CMD_JTAG_BIT_OP_RD     0xD2 // JTAG接口引脚位控制并读取命令
#define CH347_CMD_JTAG_DATA_SHIFT    0xD3 // JTAG接口数据移位命令
#define CH347_CMD_JTAG_DATA_SHIFT_RD 0xD4 // JTAG接口数据移位并读取命令

**Comment by phdussud** [comment]
Note that I am convinced that the firmware inside of the chip is broken for JTAG. The bits reads don't work at all. Byte reads work

**Comment by phdussud** [comment]
The other file of interest is contained in the CH347.ZIP on the chip vendor web site. It contains a file: CH347EVT\CH347EVT\TOOLS\CH347Demo\ExternalLib\CH347DLL_EN.H
with interesting definitions: 
#ifndef _CH341_DLL_H
typedef	struct	_USB_SETUP_PKT {				// Data request packet structure in the setup phase of USB control transfer
	UCHAR			mUspReqType;				// 00H request type
	UCHAR			mUspRequest;				// 01H request code
	union	{
		struct	{
			UCHAR	mUspValueLow;				// 02H Value parameter low byte
			UCHAR	mUspValueHigh;				// 03H Value parameter high byte
		};
		USHORT		mUspValue;					// 02H-03H value parameters
	};
	union	{
		struct	{
			UCHAR	mUspIndexLow;				// 04H index parameter low byte
			UCHAR	mUspIndexHigh;				// 05H index parameter high byte
		};
		USHORT		mUspIndex;					// 04H-05H index parameter
	};
	USHORT			mLength;					// 06H-07H data length of data stage
} mUSB_SETUP_PKT, *mPUSB_SETUP_PKT;


typedef	struct	_WIN32_COMMAND {				// Define the WIN32 command interface structure
	union	{
		ULONG		mFunction;					// Specify function code or pipe number when inputting
		NTSTATUS	mStatus;					// return operation status when output
	};
	ULONG			mLength;					// access length, return the length of subsequent data
	union	{
		mUSB_SETUP_PKT	mSetupPkt;				// Data request in the setup phase of USB control transfer
		UCHAR			mBuffer[ 512];      	// data buffer, the length is 0 to 255B
	};
} mWIN32_COMMAND, *mPWIN32_COMMAND;
// WIN32 Application layer interface command
#define		IOCTL_CH341_COMMAND		( FILE_DEVICE_UNKNOWN << 16 | FILE_ANY_ACCESS << 14 | 0x0f34 << 2 | METHOD_BUFFERED )	// private interface

#define		mWIN32_COMMAND_HEAD		mOFFSET( mWIN32_COMMAND, mBuffer )	// Header length of WIN32 command interface

#define		mCH341_MAX_NUMBER		16			// Maximum number of CH375 connected at the same time

#define		mMAX_BUFFER_LENGTH		0x1000		// The maximum length of the data buffer is 4MB

#define		mMAX_COMMAND_LENGTH		( mWIN32_COMMAND_HEAD + mMAX_BUFFER_LENGTH )	// maximum data length plus the length of the command structure header

#define		mDEFAULT_BUFFER_LEN		0x0400		// The default length of the data buffer is 1024

#define		mDEFAULT_COMMAND_LEN	( mWIN32_COMMAND_HEAD + mDEFAULT_BUFFER_LEN )	// default data length plus the length of the command structure header

// CH341 endpoint address
#define		mCH347_ENDP_DATA_UP		0x86		// The address of the data block upload endpoint of CH347
#define		mCH347_ENDP_DATA_DOWN	0x06		// The address of the data block download endpoint of CH347

// Pipeline operation command provided by equipment layer interface
#define		mPipeDeviceCtrl			0x00000004	// CH347 integrated control pipeline
#define		mPipeDataUp				0x00000006	// CH347 data block upload pipeline
#define		mPipeDataDown			0x00000007	// CH347 data block download pipeline

// Function code of application layer interface
#define		mFuncNoOperation		0x00000000	// no operation
#define		mFuncGetVersion			0x00000001	// Get the driver version number
#define		mFuncGetConfig			0x00000002	// Get the USB device configuration descriptor
#define		mFuncSetTimeout			0x00000009	// Set USB communication timeout
#define		mFuncSetExclusive		0x0000000b	// Set exclusive use
#define		mFuncResetDevice		0x0000000c	// Reset the USB device
#define		mFuncResetPipe			0x0000000d	// Reset the USB pipe
#define		mFuncAbortPipe			0x0000000e	// Cancel the data request of the USB pipe
#define		mFuncBufferMode			0x00000020	// Set the buffer upload mode and query the data length in the buffer
#define		mFuncBufferModeDn		0x00000021	// Set the buffer download mode and query the data length in the buffer
#define		mFuncGetVersionEx		0x00000022	// Get the driver version number and chip model
// USB device standard request code
#define		mUSB_CLR_FEATURE		0x01
#define		mUSB_SET_FEATURE		0x03
#define		mUSB_GET_STATUS			0x00
#define		mUSB_SET_ADDRESS		0x05
#define		mUSB_GET_DESCR			0x06
#define		mUSB_SET_DESCR			0x07
#define		mUSB_GET_CONFIG			0x08
#define		mUSB_SET_CONFIG			0x09
#define		mUSB_GET_INTERF			0x0a
#define		mUSB_SET_INTERF			0x0b
#define		mUSB_SYNC_FRAME			0x0c

// CH341 manufacturer specific request type for control transmission
#define		mCH341_VENDOR_READ		0xC0		// CH347 vendor-specific read operation through control transfer
#define		mCH341_VENDOR_WRITE		0x40		// CH347 vendor-specific write operation through control transfer

#define		mCH341A_CMD_I2C_STREAM	0xAA		// The command package of the I2C interface, starting from the secondary byte, is the I2C command stream
#define		mCH341A_CMD_UIO_STREAM	0xAB		// The command package of the UIO interface, starting from the secondary byte, is the command stream
#define		mCH341A_CMD_PIO_STREAM	0xAE		// The command package of PIO interface, starting from the secondary byte, is the data stream
// CH341A manufacturer specific request code for control transmission
#define		mCH341A_BUF_CLEAR		0xB2		// Clear incomplete data
#define		mCH341A_I2C_CMD_X		0x54		// Issue the command of I2C interface and execute it immediately
#define		mCH341A_DELAY_MS		0x5E		// Delay the specified time in microseconds
#define		mCH341A_GET_VER			0x5F		// Get chip version

#define		mCH341A_CMD_I2C_STM_STA	0x74		// Command flow of I2C interface: generate start bit
#define		mCH341A_CMD_I2C_STM_STO	0x75		// Command flow of I2C interface: generate stop bit
#define		mCH341A_CMD_I2C_STM_OUT	0x80		// Command flow of I2C interface: output data, bit 5- bit 0 is the length, subsequent bytes are data, and length 0 only sends one byte and returns an answer
#define		mCH341A_CMD_I2C_STM_IN	0xC0		// I2C interface command flow: input data, bit 5-bit 0 is the length, and 0 length only receives one byte and sends no response
#define		mCH341A_CMD_I2C_STM_MAX	( min( 0x3F, mCH341_PACKET_LENGTH ) )	// The maximum length of input and output data of a single command in the command stream of I2C interface
#define		mCH341A_CMD_I2C_STM_SET	0x60		// Command flow of I2C interface: set parameters, bit 2=i/o number of SPI (0= single input single output, 1= double input double output), bit 1 0=i2c speed (00= low speed, 01= standard, 10= fast, 11= high speed)
#define		mCH341A_CMD_I2C_STM_US	0x40		// Command flow of I2C interface: delay in microseconds, bit 3- bit 0 as delay value
#define		mCH341A_CMD_I2C_STM_MS	0x50		// Command flow of I2C interface: delay in microseconds, bit 3-bit 0 as delay value
#define		mCH341A_CMD_I2C_STM_DLY	0x0F		// Maximum value of single command delay of command flow of I2C interface
#define		mCH341A_CMD_I2C_STM_END	0x00		// Command flow of I2C interface: Command package ends in advance

#define		mCH341A_CMD_UIO_STM_IN	0x00		// Command flow of UIO interface: input data D7-D0
#define		mCH341A_CMD_UIO_STM_DIR	0x40		// Command flow of UIO interface: set i/o direction D5-D0, bit 5- bit 0 as direction data
#define		mCH341A_CMD_UIO_STM_OUT	0x80		// Command flow of UIO interface: output data D5-D0, bit 5-bit 0 is data
#define		mCH341A_CMD_UIO_STM_US	0xC0		// Command flow of UIO interface: delay in microseconds, bit 5- bit 0 as delay value
#define		mCH341A_CMD_UIO_STM_END	0x20		// Command flow of UIO interface: Command package ends in advance

#define		MAX_DEVICE_PATH_SIZE	128			// Maximum number of characters for device name
#define		MAX_DEVICE_ID_SIZE		64			// Maximum number of characters for device ID
#endif _CH341_DLL_H

//Drive Interface
#define CH347_USB_VENDOR   0
#define CH347_USB_HID      2
#define CH347_USB_VCP      3

//CH347_USB_VENDOR support CH341/7
#define CHIP_TYPE_CH341    0
#define CHIP_TYPE_CH347    1

//Chip Function Interface Number
#define CH347_FUNC_UART      0
#define CH347_FUNC_SPI_IIC   1
#define CH347_FUNC_JTAG_IIC  2

#define DEFAULT_READ_TIMEOUT  500  // Default read timeout duration (mS)
#define DEFAULT_WRITE_TIMEOUT 500  // Default write timeout duration (mS)

#define		mCH347_PACKET_LENGTH	512		// Length of packets supported by ch347
#pragma pack(1) 
//SPI Controller Configuration
typedef struct _SPI_CONFIG{
	UCHAR           iMode;                 // 0-3:SPI Mode0/1/2/3
	UCHAR           iClock;                // 0=60MHz, 1=30MHz, 2=15MHz, 3=7.5MHz, 4=3.75MHz, 5=1.875MHz, 6=937.5KHz,7=468.75KHz
	UCHAR			iByteOrder;            // 0=LSB first(LSB), 1=MSB first(MSB)
	USHORT          iSpiWriteReadInterval; // The SPI interface routinely reads and writes data command, the unit is uS
	UCHAR           iSpiOutDefaultData;    // SPI prints data by default when it reads data
	ULONG			iChipSelect;           // Piece of selected control, if bit 7 is 0, slice selection control is ignored, if bit 7 is 1, the parameter is valid: bit 1 bit 0 is 00/01 and CS1/CS2 pins are selected as low level active chip options respectively
	UCHAR           CS1Polarity;           // Bit 0: CS1 polarity control: 0: effective low level; 1: effective lhigh level;
	UCHAR           CS2Polarity;           // Bit 0: CS2 polarity control: 0: effective low level; 1: effective lhigh level;
	USHORT          iIsAutoDeativeCS;      // Whether to undo slice selection automatically after the operation is complete
	USHORT          iActiveDelay;          // Set the latency for read/write operations after slice selection,the unit is us
	ULONG           iDelayDeactive;        // Delay time for read and write operations after slice selection is unselected,the unit is us
}mSpiCfgS,*mPSpiCfgS;

//Device Information 
typedef struct _DEV_INFOR{
	UCHAR    iIndex;                 // Current open number
	UCHAR    DevicePath[MAX_PATH];   // Device link name, used for CreateFile
	UCHAR    UsbClass;               // 0:CH347_USB_CH341, 2:CH347_USB_HID,3:CH347_USB_VCP
	UCHAR    FuncType;               // 0:CH347_FUNC_UART,1:CH347_FUNC_SPI_IIC,2:CH347_FUNC_JTAG_IIC
	CHAR     DeviceID[64];           // USB\VID_xxxx&PID_xxxx
	UCHAR    ChipMode;               // Chip Mode, 0:Mode0(UART0/1); 1:Mode1(Uart1+SPI+IIC); 2:Mode2(HID Uart1+SPI+IIC) 3:Mode3(Uart1+Jtag+IIC)
	HANDLE   DevHandle;              // Device handle
	USHORT   BulkOutEndpMaxSize;     // Upload endpoint size
	USHORT   BulkInEndpMaxSize;      // The size of the downstream endpoint
	UCHAR    UsbSpeedType;           // USB Speed type,0:FS,1:HS,2:SS
	UCHAR    CH347IfNum;             // USB interface number: 0:UART,1:SPI/IIC/JTAG/GPIO
	UCHAR    DataUpEndp;             // The endpoint address
	UCHAR    DataDnEndp;             // The endpoint address
	CHAR     ProductString[64];      // Product string in USB descriptor
	CHAR     ManufacturerString[64]; // Manufacturer string in USB descriptor
	ULONG    WriteTimeout;           // USB write timeout
	ULONG    ReadTimeout;            // USB read timeout
	CHAR     FuncDescStr[64];        // Interface functions
	UCHAR    FirewareVer;            // Firmware version

}mDeviceInforS,*mPDeviceInforS;

**Comment by nic3-14159** [comment]
Thanks, I'm already aware of both of those resources. I'm currently focused on the SPI interface (both mode 1 with the VCP driver and mode 2 with the HID driver) as I am aiming to add support for the CH347 to [flashrom](https://www.flashrom.org/Flashrom). I'll get back to the other interfaces once I'm done with SPI.

> Note that I am convinced that the firmware inside of the chip is broken for JTAG. The bits reads don't work at all. Byte reads work

Yeah, I've found some other issues through my work on the SPI interface. For example, it seems to completely ignore the polarity setting you set for CS2 and uses the setting for CS1 for both chip select lines.

**Comment by phdussud** [comment]
Great! Good luck with this project. I hope they will realize how broken the current firmware is and release a fix.
