### ISSUE TITLE
Reverse-engineered CH347 SPI protocol

### ISSUE THREAD

**Issue by 981213** [nic3-14159/CH347-Research#2]
WCH doesn't remove the private structures from their Linux library which makes reverse-engineering really easy.

I've done the reverse-engineering of SPI protocol and made a SPI-NOR flash programmer using it:
https://github.com/981213/ch347-nor-prog

The ch347.c/.h is my implementation of the SPI protocol and it may be interesting for you :)

**Comment by qianfan-Zhao** [comment]
this is a flashrom portting which make ch347t supported. 
https://github.com/qianfan-Zhao/flashrom/blob/ch347/ch347t_spi.c

@nic3-14159 @981213  Thanks for yours work.
